# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: git@github.com:pre-commit/mirrors-yapf.git
    rev: v0.30.0
    hooks:
      - id: yapf
        args: ['--style=.style.yapf', '--parallel', '--in-place']
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies:  # Плагины
          - flake8-broken-line
          - flake8-builtins
          - flake8-commas
          - flake8-comprehensions
          - flake8-mutable
          - flake8-print
#          - flake8-cognitive-complexity
#          - flake8-functions
          - flake8-quotes
