site_name: corm
theme:
  name: material

repo_name: angru/corm
repo_url: https://github.com/angru/corm

nav:
  - Overview: index.md
  - Usage:
      - usage/entity.md
      - usage/relationships.md
      - usage/key-relationships.md
      - usage/hooks.md
      - usage/storage.md
  - To Be Done: to-be-done.md
  - FAQ: faq.md

markdown_extensions:
  - codehilite
  - admonition
  - markdown_include.include:
        base_path: docs
